### ISSUE TITLE
SiteId to sourceSite Comparison breaking change

### ISSUE THREAD

**Issue by adevendorf** [Goldinteractive/craft3-sitecopy#13]
Looks like the latest change completely broke the functionality of this plugin.

With Line 167 in services/SiteCopy.php (see code below), siteId is an integer, but sourceSite is a string. Changing it so it's not so strict fixes the problem.

`       
 if ($entry->siteId !== $elementSettings['sourceSite']) {
  return;
}
`

Can anyone explain the reasoning for the change, or is this a bug?

**Comment by lukasNo1** [comment]
Which craft version do you use?
I tested it with Craft 3.4.9, where the siteId is returned as string.
Craft doku says its an integer though.

I will remove the strict check for compatibility with past/future versions.

**Comment by adevendorf** [comment]
This is using the latest version as of yesterday 3.4.17.1

**Comment by adevendorf** [comment]
I should add, I noticed the plugin had stopped working before I upgraded to 3.4 as well (from 3.3.20)

**Comment by lukasNo1** [comment]
Weird. i also get a string siteId on my entries in 3.4.17.1. Gonna investigate this further.

I just released version 0.5.2, where i removed the strict check. It should work for both cases now.
