### ISSUE TITLE
Use OR instead of XOR?

### ISSUE THREAD

**Issue by MumenthalerManuel** [Goldinteractive/craft3-sitecopy#14]
I installed the plugin in one of our projects and it works very well with one exception: I would like to auto-enable the sitecopy functionality for 3 different pages (by entry type) and each of those sites should be copied from english to french and german. With the current implementation I can only choose between the following:
- 'AND', which prevents this from working completely (since no entry will match all 3 entry types)  
- **'OR' wich is acutally an 'XOR'** since it it stops looking after it finds a single rule that applies to the element
- In Theory I could probably negate the settings and list every entry type that should not be synced but that can be a lot of effort and harder to maintain.

My Questions are:
- Is there a reason why XOR is used instead of OR? 
- If yes: Would it be possible to add a normal OR and rename the current implementation to XOR?
- if no: This can be changed by simply removing lines 295-297 from services/SiteCopy.php

It would be nice to see your reasoning behind this and maybe get a change in the plugin. I'll be using my own fork until then.

**Comment by christianruhstaller** [comment]
Your requests seems reasonable we'll discuss this tomorrow and come back to you and answer your questions.

**Comment by lukasNo1** [comment]
Implemented in [0.6.0](https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.6.0)
