### ISSUE TITLE
[Feature Request] Add the ability to copy global sets from one site to another

### ISSUE THREAD

**Issue by benface** [Goldinteractive/craft3-sitecopy#15]
This plugin is great for copying content from one site to another when the content is inside an entry, but sometimes it can be inside a global set. For that reason I think it would be a great addition to allow copying global sets as well.

**Comment by christianruhstaller** [comment]
Sounds good. We'll have a look into it and will implement this feature in the near future.

**Comment by lukasNo1** [comment]
Implemented in [0.6.0](https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.6.0)
