### ISSUE TITLE
Always copy site X to site Y on save setting

### ISSUE THREAD

**Issue by shoored** [Goldinteractive/craft3-sitecopy#2]
Thanks for this plugin! It could really solve a workflow problem we have.

The setup consists of three sites, X, Y and Z.
It would be great if the plugin could provide a setting where everything in site X should be copied to site Y on save by default, and leave Z as is. 
And instead of enabling copy per entry, the option to disable this per entry.

Would this be possible somehow?

**Comment by christianruhstaller** [comment]
This workflow is quite specific. We'd need to check if there is a more general way to implement this, to reflect your workflow.

For what it seems it would go in way like that:
Add a setting for which you can define some logic to activate the site copy feature for an entry based on some properties like (section, slug, even an ID, …) and define the source and target site.

This settings shouldn't be restricted to just one.

Your workflow then could be configured as this:
criteria: * (Wildcard)
source site: X
target site: Y

If you open an entry with the source X the site copy is automatically activated and the target Y is selected. 
You still can disable it if you want to.

To consider:
- What about rights. Maybe in future releases some users aren't allowed to deactivate the copy, etc.
- If in future releases the feature of multiple copies are implemented this need to reflected on the configuration of this feature. 

I think this solution might solve your problem and could solve some other problems and could be quite an useful feature.

**Comment by shoored** [comment]
Your solution sounds awesome and is something that would be a major help in some multi-site instances. Thank you for responding and thinking with me.

**Comment by christianruhstaller** [comment]
@studiosyntax the first iteration of this feature is completed. We'd appreciate it if you could test it and give feedback.

**Comment by shoored** [comment]
@christianruhstaller Sure thing. After installing again, I don't see any AdminCP settings where I can define default options. Any additional things I need to do?

**Comment by christianruhstaller** [comment]
We didn't release a new version as for now. You should installed it and target dev-master.

**Comment by shoored** [comment]
Ah my bad. I got to that realisation last night, it was gone this morning. Will try again.

**Comment by christianruhstaller** [comment]
The feature was release in the release 0.3.0 (https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.3.0)
