### ISSUE TITLE
Deactivated fields do not get copied and creates a huge issue with Neo

### ISSUE THREAD

**Issue by christianruhstaller** [Goldinteractive/craft3-sitecopy#21]
The fix https://github.com/Goldinteractive/craft3-sitecopy/commit/93e8a313d64d87aa836d6947f69d29c1f3153bf8 introduced a new problem: Deactivated blocks do not get copied and can possibly be very problematic when copying to another site.

For further information see: https://github.com/spicywebau/craft-neo/issues/391

**Comment by lukasNo1** [comment]
Fixed in [0.6.0](https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.6.0)
