### ISSUE TITLE
Compatibility issue with Craft 3.5.5

### ISSUE THREAD

**Issue by JPrisk** [Goldinteractive/craft3-sitecopy#22]
## Expected Behavior
When editing an entry the gold sitecopy dialogue should appear on the right hand side of the editor screen and copy entries from one site to another

## Current Behavior
Gold sitecopy is not visible within the editor without the Propagation Method: 'Let each entry choose which sites it should be saved to' selected.

## Steps to Reproduce
1. Install Craft 3.5.5
2. Add plugin Gold Sitecopy

## Context (Environment)
I would like to use the plugin but am currently unable to do so.

**Comment by lukasNo1** [comment]
@JPrisk I tested this, but i cannot reproduce the issue. The dialogue should appear when there is an other site available, where the entry can be saved to.

This is not the case for example in "Only save entries to the site they were created in".
All other Propagation methods should work, if there are more than one site that fits the criteria.

Which propagation method do you use?
