### ISSUE TITLE
Error when copying Craft Commerce Product

### ISSUE THREAD

**Issue by luizhv** [Goldinteractive/craft3-sitecopy#25]
Hi there!

I'm running into an error when trying to copy a craft commerce product to another site.
Any help would be much appreciated, thanks!

Craft 3.5.15.1
Gold SiteCopy 0.6.2

![Screenshot 2020-11-25 at 8 09 14 AM](https://user-images.githubusercontent.com/1696285/100140761-433f8180-2ef6-11eb-80fa-554775015170.png)

**Comment by lukasNo1** [comment]
Thank you, we'll have a look into it and will report back as soon as possible.

**Comment by lukasNo1** [comment]
Hello, sorry for the late answer.

We could identify the issue.
It is fixed now in the new release [0.6.3](https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.6.3)
