### ISSUE TITLE
Unable to copy between site groups

### ISSUE THREAD

**Issue by saatchinorway** [Goldinteractive/craft3-sitecopy#26]
I am unsure if this is a bug or if I'm trying to do something that is not supported.

Installed plugin version 0.6.2 on Craft 3.5.17.1. It shows up on the entry I want to copy, but it only suggests copying to sites in the same site group, not the other site groups. Is this expected behaviour or have I done something wrong?

**Comment by lukasNo1** [comment]
hmm i tested it with 3.5.17.1 and it shows all sites for me, also the ones in other site groups.

Are the sites of the other group activated for the entries section?
We can only copy content to sites where the entry is enabled for.

**Comment by saatchinorway** [comment]
The entry is enabled for all the sites in question, but I found something now, it works when the entries are in a channel, but not in a structure - which is what I need it for.

So looking at for example a news item in a channel, I correctly get the list of all sites, but in a structure it only lists the site in the same site group.

**Comment by lukasNo1** [comment]
What is the propagation method of the structure in question?
The only way i could think of, is if its set to "Save entires to other sites in the same site group".
In which case you cannot copy the entry to an other site group, as it doesn't exist there.

**Comment by saatchinorway** [comment]
It is indeed "Save entries to other sites in the same site group", but the structure does exist in the other sites, it is activated for all sites.

And as I said, the settings for the channel "News" is the same, "Save entries to other sites in the same site group", and there the copy works.

**Comment by lukasNo1** [comment]
You shouldn't be able to copy any entries to another site group if the propagation method restricts it to the current group.

If you can copy your news to another group with this propagation method enabled, i suspect something is wrong with craft.
Is the news entry exactly the same on both sites (same id)?

**Comment by saatchinorway** [comment]
I must have misunderstood something when testing then, the other sites no longer show up in the list of available sites to copy to in those channels either. OK, then I know it is not supported, and will need to find another way.

**Comment by christianruhstaller** [comment]
So we'll close this for now.
