### ISSUE TITLE
Feature request - make plugin work for asset fields as well

### ISSUE THREAD

**Issue by jripmeester** [Goldinteractive/craft3-sitecopy#27]
For a client with a language heavy we've got this plugin installed to do the heavy lifting on copying base content.
As the client wants to have as much control as possible on SEO they also have a few custom fields on assets for alt texts amongst others.

Put working with 200+ customer logo's copying all of the data to every asset is quite a burden. So SiteCopy plugin asset support would be heaven!

**Comment by lukasNo1** [comment]
This seems like a useful enhancement besides the currently supported entries, global sets and commerce products.

We will have a look at it!

**Comment by lukasNo1** [comment]
We added this feature in the new release [0.6.4](https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.6.4)
