### ISSUE TITLE
SiteCopy not working on Craft CMS 3.7.10

### ISSUE THREAD

**Issue by jripmeester** [Goldinteractive/craft3-sitecopy#28]
**Current Behavior**
Using SiteCopy on a entry with selection to copy content to another site and hit save. All changed content is saved on the current but non of the content is being copied to the other selected site.

**Expected Behavior**
All content should have been copied to the entry version on the other site.

**Steps to Reproduce**
Install Craft 3.7.10
Add plugin Gold Sitecopy
Add 2 sites to the configuration
Create an entry (only title is enough) and select to copy this to an other site.
Hit save.

**Comment by jripmeester** [comment]
Really hope this can be fixed quickly. We got a client using this plugin often and we got an CMS update ready to deploy.

**Comment by emilyfitton** [comment]
We are seeing this issue as well on a site with 3.7.10. Let me know if you need any more information. It would be great to get a fix for this asap.

**Comment by eyekiller-hub** [comment]
We too are seeing this issue on our sites with 3.7.10. Let us know if you need any assistance replicating. Hope you can fix soon.

**Comment by lukasNo1** [comment]
The issue with craft 3.7 is, that now changes on the current entry are saved in a draft and a click on save will publish the draft. Before it just saved it normally. Now that the main entry is a draft too we need to have a look at what we need to change.

I'll search for a fix / new concept asap.

**Comment by lukasNo1** [comment]
In the meantime it works if you click save on your edited changes - then they are saved to the entry

now you save it a second time with the copy to site toggle enabled

**Comment by emilyfitton** [comment]
Thanks so much for having a look. I'll let the client know of this workaround in the meantime.

**Comment by EKChrisM** [comment]
The suggested fix does not work for us at Eyekiller unfortunately. It doesn't create any new entries.

**Comment by lukasNo1** [comment]
@ek-chris what are you trying to do exactly?

Sitecopy isn't for creating new entries, rather for copying the content of an entry to another site where the entry exists too.

Also, if only the title isn't copying over, go to the plugin settings and enable it. Per default, only the content (without title & slug) get copied.

**Comment by EKChrisM** [comment]
@lukasNo1 Hi, yes I have a US and a UK version of a multisite on my Craft site.

My main entry is on the US version, so I've created a blank entry with the same name as on the US version in the UK site. I've toggled the 'copy to site' button but nothing is copying across.

**Comment by christianruhstaller** [comment]
@ek-chris what do you mean with «created a blank entry»? The site copy plugin will only copy to the same entry for a different site and not a totally different entry. Craft should already created this entry and you should be able to change to this entry on the same entry. I think there is a misunderstanding. 

If you could share more infos with the steps to reproduce it would help us greatly.

**Comment by EKChrisM** [comment]
@christianruhstaller It could be that I have misunderstood this plugin, but I have attached a loom video of my process I have followed. https://www.loom.com/share/b69b2eff742f4470b88c42ce3a1ed8c4

**Comment by christianruhstaller** [comment]
Does look right. What are the settings for the propagation for this section?

**Comment by EKChrisM** [comment]
I have it set to "Let each entry choose which sites it should be saved to"

**Comment by christianruhstaller** [comment]
I think the problem could be in this option. Can you try to create the entry for the UK site manually and then copy it and look if it's working?

**Comment by EKChrisM** [comment]
I created an entry with the same name as the US site in the UK site, then went into the US and enabled the Copy lightswitch, then saved it and checked the UK entry. No content was copied across. I checked the settings of the plugin and all fields are enabled to copy across.

**Comment by christianruhstaller** [comment]
@ek-chris , as this issue is not the same as this one, could you open a new one with all the information so we can have a look at it, thanks!

**Comment by emilyfitton** [comment]
@christianruhstaller any news on this fix? Thanks

**Comment by christianruhstaller** [comment]
The fix will have a large impact on the architecture of the plugin. We are currently trying to figure out the best way to handle this smoothly with the new behavior of the drafts etc. 

For now the described workaround should be at least enable the use of the plugin. 

We will give an update as soon as possible.

**Comment by emilyfitton** [comment]
No problem, keep me updated and I'll keep the client at bay.

**Comment by lukasNo1** [comment]
This issue is now resolved in the new release [0.7.0](https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.7.0)

Sitecopy now takes the content to copy over from the provisional draft instead of the entry directly if one exists.

**Comment by eyekiller-hub** [comment]
Thanks Luke - much appreciated!

Regards
Jamie

**Comment by jripmeester** [comment]
@lukasNo1 Thanks!
