### ISSUE TITLE
Doesn't seem to work at all on Craft latest?

### ISSUE THREAD

**Issue by darylknight** [Goldinteractive/craft3-sitecopy#31]
Hi,

I was really excited to find this! We have an install where we create new sites periodically and there are a couple of hundred entries to recreate in the new site each time. That being said, I've just installed this and the docs say I should be seeing a new item in the right sidebar while editing an entry for copying to a new site, and it's just not there. Any ideas?

The section is enabled in both the old site, and the one I just created.

Craft 3.7.37
SiteCopy 0.7.0

![image](https://user-images.githubusercontent.com/1250017/159729375-87294c9d-b44b-46b3-8e0f-85f1a02e2754.png)

![image](https://user-images.githubusercontent.com/1250017/159729638-2b08edb4-5b57-44ed-8983-8803db0afb81.png)

**Comment by lukasNo1** [comment]
This is probably the same thing as [issue 30](https://github.com/Goldinteractive/craft3-sitecopy/issues/30).
We cannot create new entries at the moment if they dont already exist on the target site, this is on the roadmap though.

**Comment by darylknight** [comment]
Ok, understood - thanks for replying. Looking forward to that functionality, as I thought that was the point of the plugin.

**Comment by lukasNo1** [comment]
I'll close this for now as it will be fixed with #30
