### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by remcoov** [Goldinteractive/craft3-sitecopy#32]
Hi,

Will there be a Craft 4 version soon?

Thanks

**Comment by eyekiller-hub** [comment]
Hopefully we will get a Craft 4 update soon?

**Comment by rexterkate-adwise** [comment]
+1 for a Craft 4 version. We use it in several projects and its unmissable for our clients.

**Comment by jankohlbach** [comment]
+1 one of the last two extensions holding us back

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3). It's got over 20 votes for people to update it to Craft 4, so there's certainly interest.

If you're looking for a new home for site copy, we'd be happy to continue development at Verbb (including updating to Craft 4) - but just let us know if you've got plans to continue things and update to Craft 4! It does look like you're still working on it @lukasNo1  🙂

**Comment by tekstrand** [comment]
@lukasNo1 any word here?

**Comment by lukasNo1** [comment]
We will for sure make a craft 4 version, but i cannot give you a timeline right now, as we are currently quite occupied in other projects.

**Comment by engram-design** [comment]
Appreciate the response @lukasNo1 just good to know what your plans are. Feel free to shout out if you need a hand

**Comment by emilyfitton** [comment]
+1 for Craft 4 version

**Comment by baldhadhaval08** [comment]
+1 for Craft 4 version

**Comment by remcoov** [comment]
Beste mailer,

In verband met de zomervakantie is Obaia van 25 juli t/m 12 augustus gesloten. Vanaf 16 augustus zullen wij onze mails weer beantwoorden.

Met vriendelijke groet,
Obaia

**Comment by julianafam** [comment]
+1 for Craft 4 version - it'll be great to know if there's a timeline now as like other mentioned its holding us back from migrating as well. Thanks!

**Comment by christianruhstaller** [comment]
The timeline for now is that we want to release the plugin on the end of August (planned).

**Comment by BenPicard** [comment]
Hello! Any update on the ETA? Thank you!

**Comment by christianruhstaller** [comment]
The plugin is currently in the review. As for the craft 4 version, we decided that we switch to a paid model. With this, we will prioritize issues and feature requests. 

The new repository is found here: https://github.com/Goldinteractive/craft-sitecopy
