### ISSUE TITLE
Enhancement: Sort sites bij site groups

### ISSUE THREAD

**Issue by jripmeester** [Goldinteractive/craft3-sitecopy#37]
Our client has 14 site in a multilingual setup. We recently added new sites and they are added on the bottom of the list on the entry page. This works confusing for our client. Sorting the sites by site group might be a better UI by default and would solve our clients problem.

**Comment by lukasNo1** [comment]
This sounds like a good enhancement.

We are not updating the craft 3 version of the plugin anymore, but Im going to change this for the craft 4 version over at https://github.com/Goldinteractive/craft-sitecopy

**Comment by jripmeester** [comment]
Hi @lukasNo1 
Great to hear that. This was meant for the Craft 4 version so that would be great. Do you want me to post this issue on that repo as well?

Cheers,
John

**Comment by lukasNo1** [comment]
Yes, that would be good, then we'll close this one
