### ISSUE TITLE
Issue with NEO

### ISSUE THREAD

**Issue by jesuismaxime** [Goldinteractive/craft3-sitecopy#4]
Unable to make the plugin work with Neo (at first 'cause I cant go further)

Here's the trace I got : 
https://pastebin.com/ixh2U8Xi

**Comment by lukasNo1** [comment]
The plugin is currently not compatible with the newest Neo release, V2.3.0.

We will investigate this.

**Comment by lukasNo1** [comment]
Neo reference: spicywebau/craft-neo#206

**Comment by christianruhstaller** [comment]
vandres gave following solution in https://github.com/spicywebau/craft-neo/issues/206:
```
<?php
return [
    'saveModifiedBlocksOnly' => false,
];
```
Seems like a clean workaround for now.

**Comment by sidneywidmer** [comment]
I think this can be closed since `saveModifiedBlocksOnly` was removed in 2.3.0.1 (2019-04-11).

**Comment by christianruhstaller** [comment]
Yes it was and it seems that this broke the copy workflow for Neo fields if they aren't dirty (We are investigating this). :)

**Comment by lukasNo1** [comment]
Fixed in [0.5.3](https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.5.3)
