### ISSUE TITLE
Can't copy to multiple sites at once.

### ISSUE THREAD

**Issue by mijewe** [Goldinteractive/craft3-sitecopy#5]
It would be good to be able to copy to multiple sites at once, but the menu of sites are radios, not checkboxes.

Would this be possible?

**Comment by christianruhstaller** [comment]
It would be possible but this would be quite resource hungry. As for now what happens is that we simulate a save on the specific entry with the copied content. Depending on the hosting this could take a long time and maybe result in a timeout. 

The solution could be in using a queue. And see how it works. For now we add it as an enhancement.

**Comment by amityweb** [comment]
Is there an update to this? I have a customer who will want to copy content to many other language sites the same time, so could it be added? Guess all it needs is checkboxes then a loop through them instead of one main process on a radio item. 
Thanks

**Comment by christianruhstaller** [comment]
We will implement this feature. It should be released in the next week or so.

**Comment by amityweb** [comment]
I can see it does take a bit of time for just one site so agree it would not be good to have multiple sites unless you send it off to the queue. Its not that urgent for my site now actually, they will do one at a time.

**Comment by christianruhstaller** [comment]
We released the version 0.4.0 and now it's possible to copy an entry to multiple site at once. 
This uses the queue and it can be that it needs a little bit time until all of the copies are finished.
https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.4.0
