### ISSUE TITLE
Issue with Neo blocks when not managed on a per-site basis

### ISSUE THREAD

**Issue by lukasNo1** [Goldinteractive/craft3-sitecopy#6]
Craft 3.2.4.1
Neo 2.3.6
If we want to copy a neo block, that is not saved on a per-site basis, neo throws an error "Invalid owner ID".

Side note: Resave entries when changing a neo block to "manage on a per-site basis", else the content will get deleted.

**Comment by nitech** [comment]
Also having this problem. Possibly related to #237

![image](https://user-images.githubusercontent.com/1279436/62459805-97ae7300-b780-11e9-8726-3f0ed63b0c78.png)

**Comment by lukasNo1** [comment]
Neo 2.4.0 seems to fix this.
