### ISSUE TITLE
Missing on eCommerce Products

### ISSUE THREAD

**Issue by amityweb** [Goldinteractive/craft3-sitecopy#7]
Th Copy link does not seem to be added to Products in Crafts eCommerce plugin?

**Comment by christianruhstaller** [comment]
This is correct. This plugin works currently only on default Craft entries.

**Comment by amityweb** [comment]
I have modified the plugin to make it work for Products, I will try to send a PR so you can ensure to add it in, in case you update the plugin I would not want my changes wiped out. 
Thanks

**Comment by christianruhstaller** [comment]
The release 0.4.0 includes the commerce compatibility https://github.com/Goldinteractive/craft3-sitecopy/releases/tag/0.4.0
